In [1]:
import numpy as np
 
arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print(arr1)  # [1 2 3 4 5]
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [2]:
np.zeros((3, 3))  

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full((2, 2), 10) 

array([[10, 10],
       [10, 10]])

In [6]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
# print("Shape:", arr.shape)
# print("Size:", arr.size)   
# print("Dimensions:", arr.ndim
print("Data type:", arr.dtype) 

Data type: int64
