In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [5]:
arr = np.array([10, 20, 30, 40, 50])

# print(arr[1:4])
# print(arr[:3]) 
# print(arr[::2])


[10 30 50]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
sliced = arr[1:4].copy()
sliced[0]=999
print(arr)

[10 20 30 40 50]


In [9]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [12]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr <=30  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[10 20 30]


In [14]:
a=np.full((3,3),4)

In [15]:
a.shape

(3, 3)

In [16]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [19]:
a=np.array([1.1, 2.2, 3.3],dtype=np.float32)
a_int=a.astype(np.int32)
print(a_int)

[1 2 3]


In [21]:
b=np.array([1, 2, 3, 4, 5, 6])
idx=[1,3,5]
print(b[idx])

[2 4 6]


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9])
b=arr.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
