In [1]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.sum(arr,axis=0))

[12 15 18]


In [3]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [4]:
print(arr[1,2])

6


In [5]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [6]:
print(arr[1:3,0:2])

[[4 5]
 [7 8]]


In [8]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
print(arr3D.shape)

(2, 2, 3)


In [9]:
print(arr3D[0, 1, 2])

6


In [10]:
print(arr3D[:, 0, :]) 

[[1 2 3]
 [7 8 9]]
